steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '--build-arg=NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyA7vzoat4KDuQEfxmL3cbhOnRBaC3oox3c'
    - '--build-arg=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=aura-501017.firebaseapp.com'
    - '--build-arg=NEXT_PUBLIC_FIREBASE_PROJECT_ID=aura-501017'
    - '--build-arg=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=aura-501017.firebasestorage.app'
    - '--build-arg=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=73719509839'
    - '--build-arg=NEXT_PUBLIC_FIREBASE_APP_ID=1:73719509839:web:54d85a6a11d587e0ee0b3a'
    - '--build-arg=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-H0P60SPX32'
    - '-t'
    - 'gcr.io/aura-501017/aura'
    - '.'

images:
- 'gcr.io/aura-501017/aura'
